### PR TITLE
Bump deps: fontconfig (switch to meson, patch known leaks)

### PR DESCRIPTION
**Pull request by lovell**
Adds 4 patches made to fontconfig's `main` branch since v2.13.94.

### CODE REVIEW

**Review by kleisauke — APPROVED** [review]
LGTM!

**Comment by lovell** [comment]
Thanks, it's removed most of the memory leaks I was previously seeing, but we're still impacted by what I think is caused by https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/302

```
==102705== 321 bytes in 32 blocks are indirectly lost in loss record 8,127 of 8,480
==102705==    at 0x52A5045: malloc (vg_replace_malloc.c:381)
==102705==    by 0x573A50E: strdup (strdup.c:42)
==102705==    by 0x12B3EDFC: FcValueSave
==102705== 
```

Rather luckily this has just been fixed upstream so I'll add this patch too.

https://gitlab.freedesktop.org/fontconfig/fontconfig/-/merge_requests/220

**Comment by kleisauke** [comment]
If preferred, I could make a v8.12.2-build2 release at https://github.com/libvips/build-win64-mxe with the same patches incorporated (+ glib, expat and lcms2 version bumps).

**Comment by lovell** [comment]
Yes please, that would be great.

**Comment by kleisauke** [comment]
https://github.com/libvips/build-win64-mxe/releases/tag/v8.12.2-build2 :tada:

**Pull request merged**
