### PR TITLE
macOS: remove version requirement for Meson

### PR DESCRIPTION
**Pull request by kleisauke**
Skipping this version is now implicitly done since Meson 0.63.2
was released, which reverted the commit that caused this linker
failure.

See: https://github.com/mesonbuild/meson/commit/0e0dbf7e35f1e368090682bfd4818589d3c64d6e

### CODE REVIEW

**Comment by lovell** [comment]
Ah ha, that'll probably be it. I was down a rabbit hole investigating to see if the upgrade from rust 1.62.1 to 1.63.0 had somehow altered symbol visibility.

**Comment by eli-schwartz** [comment]
```
[357/363] Linking static target libvips/libvips.a
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(analyze2vips.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(fits.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(matlab.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(openexr2vips.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(pdfiumload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(radiance.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick2vips.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick6load.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick7load.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(vips2magick.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(jxlload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(jxlsave.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(popplerload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(openslideload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(analyze2vips.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(fits.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(matlab.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(openexr2vips.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(pdfiumload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(radiance.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick2vips.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick6load.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(magick7load.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(vips2magick.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(jxlload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(jxlsave.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(popplerload.c.o) has no symbols
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvips/libvips.a(openslideload.c.o) has no symbols
```
This seems concerning as well. Seems like running ranlib might be broken??

**Comment by eli-schwartz** [comment]
A more exacting test would be to `pip install git+https://github.com/eli-schwartz/meson@libvips-applear`, see https://github.com/eli-schwartz/meson/commits/libvips-applear

**Comment by eli-schwartz** [comment]
Well, that commit is confirmed to have broken it...

Why, Apple, why.

**Comment by eli-schwartz** [comment]
```
duplicate symbol '_vips_LabQ2sRGB_get_type' in:
    libvips/libvips.a(LabQ2sRGB.c.o)
    libvips/colour/libcolour.a(LabQ2sRGB.c.o)
```

Why is this in both static archives?

Why *only* when running ranlib -c?

**Comment by dcbaker** [comment]
For the `warning no symbols`, it appears that Apple's ranlab has an argument to silence that warning, so we should check for that and add it if it exists

**Comment by dcbaker** [comment]
If you remove the `s` from the `ar` arguments in the build.ninja, does it work correctly?

**Comment by dcbaker** [comment]
or, can you run with this branch and see if that fixes the issue? https://github.com/dcbaker/meson/tree/submit/apple-ar-dont-ranlib

I don't have access to a mac anymore, so it's kinda hard for me to test

**Comment by dcbaker** [comment]
Why is it linking both `libvips.a` *and* the individual static conveience libraries? that looks like some kind of meson bug that running ranlib -c simply exposed due to force duplicate symbols to be present.

**Comment by dcbaker** [comment]
I think I've figured out what's happening, and it's an old bug in meson around an optimization we do with convenienve libraries. I've repushed my branch, can you try again with the current HEAD?

**Comment by kleisauke** [comment]
It looks like commit https://github.com/dcbaker/meson/commit/40c37d10af144b27b3e67e659ab42b2b7e8ab0af worked.

**Comment by kleisauke** [comment]
... and confirmed that it does not cause regressions on Linux.

Let me know if I need to test other branches or (pre-)releases as well.

**Comment by dcbaker** [comment]
Thanks for testing, I really appreciate it. I've opened a [PR](https://github.com/mesonbuild/meson/pull/10699) and tagged it for inclusion in the next stable 0.63 release (0.63.2), so it should be sufficient to just blacklist the 0.63.1 release, and get 0.63.2 when it becomes avilable. something like this: `pip install meson!=0.63.1`

**Comment by lovell** [comment]
Thanks all, as suggested I've temporarily prevented the use of meson 0.63.1 via commit https://github.com/lovell/sharp-libvips/commit/a9c12f8441936f6287411893c055e8de15649b04 to get things moving again. Let's keep this PR open to verify the next meson release and then remove the version block.

**Comment by kleisauke** [comment]
I've removed the version requirement and updated this PR accordingly now that Meson 0.63.2 has been released, which reverted the commit that caused this linker failure.

**Pull request merged**
