### PR TITLE
Upgrade dep: harfbuzz

### PR DESCRIPTION
**Pull request by kleisauke**
And use Meson as build system. I've disabled the utils to fix the linker errors, but perhaps this should be reported upstream.

### CODE REVIEW

**Comment by lovell** [comment]
Thank you for working out the source of the linker errors.

**Comment by kleisauke** [comment]
The patch from https://github.com/Homebrew/linuxbrew-core/pull/20910 should fix the [Linux ARMv6 build failures](https://github.com/lovell/sharp-libvips/runs/970931822), I think. Should I prepare a PR for that?

**Comment by lovell** [comment]
Yes please. (I added commit 07420d5 to attempt to silence these.)

**Comment by lovell** [comment]
This is being fixed upstream via https://github.com/harfbuzz/harfbuzz/pull/2628 so we could use https://patch-diff.githubusercontent.com/raw/harfbuzz/harfbuzz/pull/2628.diff as the patch.

**Comment by lovell** [comment]
Let's wait for harfbuzz 2.7.1, which should be available soon. There's some discussion about the recent meson-only change at https://github.com/harfbuzz/harfbuzz/pull/2632 which suggests it was a bit rushed and did not have approval (or at least had not been reviewed).

**Pull request merged**
