### PR TITLE
Meson: uses system directories in machine files

### PR DESCRIPTION
**Pull request by kleisauke**
Noticed this while doing:
```console
$ mkdir linux-x64
$ curl -fsSL https://github.com/lovell/sharp-libvips/releases/download/v8.15.2/libvips-8.15.2-linux-x64.tar.gz | tar xzC linux-x64
$ strings linux-x64/lib/libvips-cpp.so.42 | grep "/fontconfig"
  <dir prefix="xdg">fonts</dir>  <cachedir>/target/var/cache/fontconfig</cachedir>  <cachedir prefix="xdg">fontconfig</cachedir>  <include ignore_missing="yes">/etc/fonts/conf.d</include>  <include ignore_missing="yes" prefix="xdg">fontconfig/conf.d</include>  <include ignore_missing="yes" prefix="xdg">fontconfig/fonts.conf</include></fontconfig>
/target/share/fontconfig/conf.avail
/target/var/cache/fontconfig
/fontconfig
```

With this PR, I see:
```console
$ strings libvips-8.15.2-linux-x64/lib/libvips-cpp.so.42 | grep "/fontconfig"
  <dir prefix="xdg">fonts</dir>  <cachedir>/var/cache/fontconfig</cachedir>  <cachedir prefix="xdg">fontconfig</cachedir>  <include ignore_missing="yes">/etc/fonts/conf.d</include>  <include ignore_missing="yes" prefix="xdg">fontconfig/conf.d</include>  <include ignore_missing="yes" prefix="xdg">fontconfig/fonts.conf</include></fontconfig>
/usr/share/fontconfig/conf.avail
/var/cache/fontconfig
/fontconfig
```

And this during configuring Fontconfig:
```diff
   Paths
-    Cache directory            : /target/var/cache/fontconfig
-    Template directory         : /target/share/fontconfig/conf.avail
+    Cache directory            : /var/cache/fontconfig
+    Template directory         : /usr/share/fontconfig/conf.avail
     Base config directory      : /etc/fonts
     Config directory           : /etc/fonts/conf.d
-    XML directory              : /target/share/xml/fontconfig
+    XML directory              : /usr/share/xml/fontconfig
```

### CODE REVIEW

**Comment by kleisauke** [comment]
FWIW, `grep`-ing for `/target` would still result in:
```console
$ strings libvips-8.15.2-linux-x64/lib/libvips-cpp.so.42 | grep "/target"
/target/share/color/icc
/target
/target/lib
/target/share/locale
/target/var/lib/dbus/machine-id
/target/var
/dev/shm/journal9999-12-31T23:59/target/lib/gio/k
```

The first three paths are from libvips and correspond to `VIPS_ICC_DIR`, `VIPS_PREFIX` and `VIPS_LIBDIR`.
https://github.com/libvips/libvips/blob/c1565644277792804b73d11242bed3e1414f86ff/meson.build#L682
https://github.com/libvips/libvips/blob/c1565644277792804b73d11242bed3e1414f86ff/libvips/iofuncs/util.c#L1976
https://github.com/libvips/libvips/blob/c1565644277792804b73d11242bed3e1414f86ff/meson.build#L655-L656
https://github.com/libvips/libvips/blob/c1565644277792804b73d11242bed3e1414f86ff/libvips/iofuncs/init.c#L552-L553

The next three paths are from GLib and correspond to `GLIB_LOCALE_DIR`, `GLIB_LOCALSTATEDIR`.
https://github.com/GNOME/glib/blob/e124c34ad6d04c725a0e6f46c2b8934838af04ef/meson.build#L2285-L2288
https://github.com/GNOME/glib/blob/e124c34ad6d04c725a0e6f46c2b8934838af04ef/glib/ggettext.c#L72
https://github.com/GNOME/glib/blob/e124c34ad6d04c725a0e6f46c2b8934838af04ef/gio/gdbusprivate.c#L2452
https://github.com/GNOME/glib/blob/e124c34ad6d04c725a0e6f46c2b8934838af04ef/gio/gunixmounts.c#L271

The last one I'm not sure about, but it probably corresponds to `GIO_MODULE_DIR`.
https://github.com/GNOME/glib/blob/e124c34ad6d04c725a0e6f46c2b8934838af04ef/gio/giomodule.c#L1261

**Comment by lovell** [comment]
Excellent detective work Kleis. Given we're always overriding `--prefix` for meson-based dependencies, perhaps we should be setting these options to all meson-compiled dependencies e.g. via `meson.ini`?

**Comment by kleisauke** [comment]
Good idea! Just updated this PR to set these options in the Meson machine files instead. I now see:
```console
$ strings libvips-8.15.2-linux-x64/lib/libvips-cpp.so.42 | grep "/target"
/target
/target/lib
/dev/shm/journal9999-12-31T23:59/target/lib/gio/k
```

**Comment by lovell** [comment]
Brilliant, thanks for spotting/fixing this.

**Pull request merged**
